export enum Roles {
    CUSTOMER = 'CUSTOMER',
    RESTAURANT_OWNER = 'RESTAURANT_OWNER',
    DELIVERY_MAN = 'DELIVERY_MAN',
    TECHNICAL_DEPARTMENT = 'TECHNICAL_DEPARTMENT',
    COMERCIAL_DEPARTMENT = 'COMERCIAL_DEPARTMENT',
    EXTERNAL = 'EXTERNAL'
}